### PR TITLE
Renamed 'countries' attribute to 'iso3_codes'in RegionCode class

### LINKED ISSUE #251: Use different name for ISO3-code attribute
Per a discussion at the ECEMF Consortium Meeting: the reserved word "countries" for the list of ISO3-codes is not ideal, because it is not obvious that only ISO3-codes are allowed.

Please change the package such that the reserved-word (including the validation) hinges on the term "iso3" instead.

### PR DESCRIPTION
**Pull request by GretchenSchowalter**
Hey, Daniel! This is a quick PR to address issue #251. I changed the attribute name from _countries_ to _iso3_codes_. Let me know if anything else needs to be changed!

closes #251

### CODE REVIEW

**Review by danielhuppmann — APPROVED** [review]
Looks good to me, thanks!

**Comment by danielhuppmann** [comment]
@phackstock, are you ok with this change?

**Review by phackstock — APPROVED** [review]
@GretchenSchowalter, thanks for the quick work :+1: 
@danielhuppmann no major objections from my side. 
The only thing that I would change is the name of the attribute. `iso3_codes` sounds a little ambiguous to me. 
Something like `constituent_regions_in_iso3` would be longer but less ambiguous. 
No strong preference though, I'd totally be fine with `iso3_codes` as well.

**Comment by danielhuppmann** [comment]
Thanks @phackstock - I think that your suggestion is unreadably long given that most values will be just 3 digits... But we can add some documentation later.

**Pull request merged**
