### PR TITLE
Simplify Code.attributes type hint

### LINKED ISSUE #191: Simplify Code.attributes type hint
Now that `Code.attributes` is only used to hold additional dict style named attributes and no longer values related to region processing we should be able to simplify the type hint from:
https://github.com/IAMconsortium/nomenclature/blob/70cbe0b3651a486d3fabdc52e3af2e0ed8be0347/nomenclature/code.py#L11-L28

```python
attributes: Dict = {}
```

### PR DESCRIPTION
**Pull request by phackstock**
closes #191.

Mostly self explanatory, since `Code.attributes` does no longer need to support more complex region aggregation related data structures we can simplify the type hint.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Just to be sure, this typehint has no functional implications, right?

**Comment by phackstock** [comment]
> Just to be sure, this typehint has no functional implications, right?

In the pure python sense this does not have any implications. By using pydantic it _can_ have some functional implications. In the order of definition of options for data types in Union, pydantic will attempt type conversion.

As an example if we have:

```python
from pydantic import BaseModel

class A(BaseModel):
    a: Union[int, str]

instance_A = A(a = "3") 
print(type(A.a)) >>> "int"
```

pydantic converts the string "3" into the integer 3. 

This might have actually had a functional use in the past where we had attributes such as `check-aggregate` in the `attributes` object. Now that this is only used to hold additional, non-nomenclature functional information, it _should_ not have any functional implications.

**Review by danielhuppmann — APPROVED** [review]
Thanks @phackstock, looks good!

**Comment by phackstock** [comment]
Seems like resolving the merge conflicts blew up something, I'll investigate.

**Pull request merged**
