### PR TITLE
Correct test pypi installation test

### PR DESCRIPTION
**Pull request by phackstock**
This is a tiny correction to DEVELOPING.rst. As the tests are not bundled with the package you cannot check that the tests are working.

### CODE REVIEW

**Review by danielhuppmann — APPROVED** [review]
Good catch! Maybe create an issue so that this can be tackled at some point?

**Comment by phackstock** [comment]
> Maybe create an issue so that this can be tackled at some point?

Do you mean we should bundle the tests with the package? I was under the impression that that's not standard practice.

**Comment by danielhuppmann** [comment]
Ok, then let's not do this...

**Comment by phackstock** [comment]
Alright, sounds good. I just double checked and it does not seem like pyam includes the tests either.

**Pull request merged**
