### PR TITLE
Add readthedocs.yml for documentation build

### PR DESCRIPTION
**Pull request by LauWien**
This PR adds the _readthedocs.yml_ file for the documentation build on [RTD](https://readthedocs.org/). It supports the closing of issue #53.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Looks good! But how about adding a build-the-docs GitHub Actions workflow, like https://github.com/IAMconsortium/pyam/blob/main/.github/workflows/build-docs.yml?

**Review by danielhuppmann — APPROVED** [review]
Looks good to me!

**Comment by phackstock** [comment]
Just for understanding, this build-docs.yml is only for assuring that the docs can be built without any errors right? It does not do anything with the docs once they are built, correct?

**Comment by danielhuppmann** [comment]
Correct, @phackstock:
 - RTD only sphinx-builds the docs **after** a PR is merged and does not raise an error if a build fails.
 - The additional GitHub Action workflow ensures that the sphinx-build succeeds **before** a PR is merged.

Technically speaking, because GitHub Action uses a slightly configuration from RTD, this will not cause all problems - but it saved me from a few silly mistakes in the past. What I did in the past if I really wanted to be sure about what will happen on RTD: create a branch on upstream (rather than my fork) and to add the branch to the list of branches built by RTD before starting a PR. See a real-world example here: https://github.com/IAMconsortium/pyam/pull/564 - though, usually, I then remove the branch from RTD again after merging the PR.

**Comment by LauWien** [comment]
Thank you @danielhuppmann for reviewing!

**Pull request merged**
