### PR TITLE
Refactor class name to "DataStructureDefinition"

### PR DESCRIPTION
**Pull request by danielhuppmann**
This PR implements a suggestion by @khaeru in #18 to bring this package closer in line with the SDMX standard.

*Warning: upon merging, the workflow-repos using this package must be updated.*

### CODE REVIEW

**Comment by phackstock** [comment]
Looks good to me. I'll make sure that [irp-internal](https://github.com/iiasa/irp-internal) is updated accordingly.
One quick question about the usage of ` # noqa` in `nomenclature/__init__.py`. Does this tell stickler to ignore this line in its checks?

**Comment by danielhuppmann** [comment]
> One quick question about the usage of ` # noqa` in `nomenclature/__init__.py`. Does this tell stickler to ignore this line in its checks?

Yes, see @stickler-ci on the previous commit at https://github.com/IAMconsortium/nomenclature/pull/21/checks?sha=520cb146e43106f4d33d893a07c65047f2a29cee

There may be smarter ways to do this, but this worked for me...

**Comment by phackstock** [comment]
Ah alright, then I would say looks good to me

**Review by phackstock — APPROVED** [review]
Just realized that my previous comment was not an actual review.
All good from my side.

**Comment by phackstock** [comment]
Should we merge and update the corresponding workflows?

* [irp-internal](https://github.com/iiasa/irp-internal-workflow)
* [emf37-internal](https://github.com/iiasa/emf37-workflow)
* [jmip-internal](https://github.com/iiasa/jmip-internal-workflow)

**Comment by phackstock** [comment]
Updated the three dependent workflows

**Pull request merged**
